apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: konga
    track: konga-stable
  name: konga-stable
  namespace: konga
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: konga
      track: konga-stable
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: konga
        track: konga-stable
    spec:
      containers:
      - env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: NODE_ENV
          value: "production"
        name: konga
        image: pantsel/konga
        ports:
        - name: http
          containerPort: 1337
          protocol: TCP
